// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhWmg0keBP_RpbtDyuKUdCtiq6VRmaMk',
    appId: '1:668062751811:web:345883e2b35bf3418388f6',
    messagingSenderId: '668062751811',
    projectId: 'nontonanime-58c76',
    authDomain: 'nontonanime-58c76.firebaseapp.com',
    storageBucket: 'nontonanime-58c76.firebasestorage.app',
    measurementId: 'G-NERXK1XDZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4fR52qo7RrVHPa5do60l9qF1W-vXXsQ',
    appId: '1:668062751811:android:8d54b6dc595d7ff98388f6',
    messagingSenderId: '668062751811',
    projectId: 'nontonanime-58c76',
    storageBucket: 'nontonanime-58c76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh273xmonnt5ardrI1CXenvdMyS43M-NY',
    appId: '1:668062751811:ios:f7bf0be23ad035a68388f6',
    messagingSenderId: '668062751811',
    projectId: 'nontonanime-58c76',
    storageBucket: 'nontonanime-58c76.firebasestorage.app',
    iosBundleId: 'com.example.diotest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh273xmonnt5ardrI1CXenvdMyS43M-NY',
    appId: '1:668062751811:ios:f7bf0be23ad035a68388f6',
    messagingSenderId: '668062751811',
    projectId: 'nontonanime-58c76',
    storageBucket: 'nontonanime-58c76.firebasestorage.app',
    iosBundleId: 'com.example.diotest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMhWmg0keBP_RpbtDyuKUdCtiq6VRmaMk',
    appId: '1:668062751811:web:4763684b78570fdc8388f6',
    messagingSenderId: '668062751811',
    projectId: 'nontonanime-58c76',
    authDomain: 'nontonanime-58c76.firebaseapp.com',
    storageBucket: 'nontonanime-58c76.firebasestorage.app',
    measurementId: 'G-WQ5NFG97C2',
  );
}
